ament_prepend_unique_value GAZEBO_MODEL_PATH "/home/zhettus/ros2_ws/install/husarion_gz_worlds/share/husarion_gz_worlds/models"
ament_prepend_unique_value GZ_SIM_RESOURCE_PATH "/home/zhettus/ros2_ws/install/husarion_gz_worlds/share/husarion_gz_worlds/models"
ament_prepend_unique_value IGN_GAZEBO_RESOURCE_PATH "/home/zhettus/ros2_ws/install/husarion_gz_worlds/share/husarion_gz_worlds/models"
